
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzsdjyhiomkxjzaruhsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6c2RqeWhpb21reGp6YXJ1aHN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI5MTEzMzMsImV4cCI6MjA1ODQ4NzMzM30.bcTPNevS7R1Og6HtJp7bYRTbSJ2jIUq8TDEcYXyfclM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with anonymous permissions for public data access
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // We'll still use localStorage for persistence but won't rely on it for authentication
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
